<div class="page-title">
    <h1><?php echo Mage::helper('Speroteck_Request')->__('Catalog Request') ?></h1>
</div>

<form action="<?php echo $this->getUrl('requestform/index/send'); ?>" id="requestForm" method="post">

    <div class="fieldset">
        <h2 class="legend"><?php echo Mage::helper('Speroteck_Request')->__('Request Information') ?></h2>
        <p class="required"><?php echo Mage::helper('Speroteck_Request')->__('* Required Fields') ?></p>

        <ul class="form-list">
            <li class="fields">
                <div class="field">
                    <label for="name" class="required"><em>*</em><?php echo Mage::helper('Speroteck_Request')->__('Name') ?></label>
                    <div class="input-box">
                        <input name="name" id="name" title="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('Speroteck_Request')->__('Name')) ?>" value="" class="input-text" type="text" />
                    </div>
                </div>
                <div class="field">
                    <label for="email" class="required"><em>*</em><?php echo Mage::helper('Speroteck_Request')->__('Email') ?></label>
                    <div class="input-box">
                        <input name="email" id="email" title="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('Speroteck_Request')->__('Email')) ?>" value="" class="input-text" type="text" />
                    </div>
                </div>
                <div class="field">
                    <label for="address_line_1" class="required"><em>*</em><?php echo Mage::helper('Speroteck_Request')->__('Address 1') ?></label>
                    <div class="input-box">
                        <input name="address_line_1" id="address_line_1" title="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('Speroteck_Request')->__('Address 1')) ?>" value="" class="input-text" type="text" />
                    </div>
                </div>
                <div class="field">
                    <label for="address_line_2"> <?php echo Mage::helper('Speroteck_Request')->__('Address 2') ?></label>
                    <div class="input-box">
                        <input name="address_line_2" id="address_line_2" title="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('Speroteck_Request')->__('Address 2')) ?>" value="" class="input-text" type="text" />
                    </div>
                </div>
                <div class="field">
                    <label for="city" class="required"><em>*</em><?php echo Mage::helper('Speroteck_Request')->__('City') ?></label>
                    <div class="input-box">
                        <input name="city" id="city" title="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('Speroteck_Request')->__('City')) ?>" value="" class="input-text" type="text" />
                    </div>
                </div>
                <div class="field">
                    <label for="region" class="required"><em>*</em><?php echo Mage::helper('Speroteck_Request')->__('State/Province') ?></label>
                    <div class="input-box">
                        <input name="region" id="region" title="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('Speroteck_Request')->__('State/Province')) ?>" value="" class="input-text" type="text" />
                    </div>
                </div>
                <div class="field">
                    <label for="country" class="required"><em>*</em><?php echo Mage::helper('Speroteck_Request')->__('Country') ?></label>
                    <div class="input-box">
                        <input name="country" id="country" title="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('Speroteck_Request')->__('Country')) ?>" value="" class="input-text" type="text" />
                    </div>
                </div>
                <div class="postcode">
                    <label for="region" class="required"><em>*</em><?php echo Mage::helper('Speroteck_Request')->__('Post Code') ?></label>
                    <div class="input-box">
                        <input name="postcode" id="postcode" title="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('Speroteck_Request')->__('Post Code')) ?>" value="" class="input-text" type="text" />
                    </div>
                </div>
            </li>
            <li>
                <label for="phone"><?php echo Mage::helper('Speroteck_Request')->__('Phone') ?></label>
                <div class="input-box">
                    <input name="phone" id="phone" title="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('Speroteck_Request')->__('Phone')) ?>" value="" class="input-text" type="text" />
                </div>
            </li>
        </ul>
    </div>
    <div class="buttons-set">
        <input type="text" name="hideit" id="hideit" value="" style="display:none !important;" />
        <button type="submit" title="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('Speroteck_Request')->__('Submit')) ?>" class="button"><span><span><?php echo Mage::helper('Speroteck_Request')->__('Submit') ?></span></span></button>
    </div>
</form>
<!--<script type="text/javascript">-->
<!--    //<![CDATA[-->
<!--    var contactForm = new VarienForm('contactForm', true);-->
<!--    //]]>-->
<!--</script>-->
